//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIncediosUME_JorgePrieto
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        public localidad()
        {
            this.datoMeteorologico = new HashSet<datoMeteorologico>();
            this.Incendio = new HashSet<Incendio>();
        }
    
        public int idLocalidad { get; set; }
        public int idProvincia { get; set; }
        public string nombreLocalidad { get; set; }
        public Nullable<int> temperaturaMediaPrimavera { get; set; }
        public Nullable<int> humedadMediaPrimavera { get; set; }
        public Nullable<int> temperaturaMediaVerano { get; set; }
        public Nullable<int> humedadMediaVerano { get; set; }
        public Nullable<int> temperaturaMediaOtoño { get; set; }
        public Nullable<int> humedadMediaOtoño { get; set; }
        public Nullable<int> temperaturaMediaInvierno { get; set; }
        public Nullable<int> humedadMediaInvierno { get; set; }
    
        public virtual ICollection<datoMeteorologico> datoMeteorologico { get; set; }
        public virtual ICollection<Incendio> Incendio { get; set; }
        public virtual provincia provincia { get; set; }
    }
}
