//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIncediosUME_JorgePrieto
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincia
    {
        public provincia()
        {
            this.localidad = new HashSet<localidad>();
        }
    
        public int idProvincia { get; set; }
        public string nombreProvincia { get; set; }
    
        public virtual ICollection<localidad> localidad { get; set; }
    }
}
