//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIncediosUME_JorgePrieto
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string correoUsuario { get; set; }
        public string contrasenaUsuario { get; set; }
        public string activo { get; set; }
    }
}
